---
version: '2'
exclude_patterns:
  - "**/node_modules/"
  - "**/dist/"
  - "**/generated/"
  - "**/coverage/"
  - "**/*.spec.{ts,tsx}"
  # I18next config files are considered as duplication
  - "**/i18next.ts"
