version: '3'

services:
  web:
    build: .
    image: visiblehq/web
    restart: always
    env_file: .env
    privileged: true
    # https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#tips
    shm_size: '2gb'
    ports:
      - '3000:3000'
      - '4000:4000'
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/home/visible/app/packages/@visi/web-server/logs
      - ./static:/home/visible/app/packages/@visi/web-server/static
      - ./credentials:/home/visible/credentials

  postgres:
    image: postgres:12.2
    environment:
      POSTGRES_USER: visible
      POSTGRES_PASSWORD: visible
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.0
    volumes:
      - ./redis:/data
